//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlterianEMAPIClient.DMPlus {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DMEventExportFilter", Namespace="http://schemas.datacontract.org/2004/07/DMLibrary")]
    [System.SerializableAttribute()]
    public partial class DMEventExportFilter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlterianEMAPIClient.DMPlus.DMEventExportFilterType FilterTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ValuesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlterianEMAPIClient.DMPlus.DMEventExportFilterType FilterType {
            get {
                return this.FilterTypeField;
            }
            set {
                if ((this.FilterTypeField.Equals(value) != true)) {
                    this.FilterTypeField = value;
                    this.RaisePropertyChanged("FilterType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Values {
            get {
                return this.ValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.ValuesField, value) != true)) {
                    this.ValuesField = value;
                    this.RaisePropertyChanged("Values");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DMEventExportFilterType", Namespace="http://schemas.datacontract.org/2004/07/DMLibrary")]
    public enum DMEventExportFilterType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEF_INCLUDE_EVENTS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEF_EXCLUDE_EVENTS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEF_INCLUDE_DEPLOYMENTS = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEF_EXCLUDE_DEPLOYMENTS = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DMRecipientColumn", Namespace="http://schemas.datacontract.org/2004/07/DMLibrary")]
    [System.SerializableAttribute()]
    public partial class DMRecipientColumn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlterianEMAPIClient.DMPlus.DMRecipientColumnType ColumnTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FieldIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ListIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlterianEMAPIClient.DMPlus.DMRecipientColumnType ColumnType {
            get {
                return this.ColumnTypeField;
            }
            set {
                if ((this.ColumnTypeField.Equals(value) != true)) {
                    this.ColumnTypeField = value;
                    this.RaisePropertyChanged("ColumnType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FieldID {
            get {
                return this.FieldIDField;
            }
            set {
                if ((this.FieldIDField.Equals(value) != true)) {
                    this.FieldIDField = value;
                    this.RaisePropertyChanged("FieldID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ListID {
            get {
                return this.ListIDField;
            }
            set {
                if ((this.ListIDField.Equals(value) != true)) {
                    this.ListIDField = value;
                    this.RaisePropertyChanged("ListID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DMRecipientColumnType", Namespace="http://schemas.datacontract.org/2004/07/DMLibrary")]
    public enum DMRecipientColumnType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMRC_RECIPIENT_ID = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMRC_PREFERTEXT = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMRC_RSSONLY = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMRC_VERIFIED = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMRC_IP = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMRC_OS = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMRC_WB_TOKEN = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMRC_WB_VALUE = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMRC_PK = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMRC_ENABLED = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMRC_CREATED = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMRC_MODIFIED = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMRC_FIELD_TOKEN = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMRC_FIELD_VALUE = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMRC_EMAIL_HEALTH = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMRC_EMAIL_DOMAIN_TOKEN = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMRC_EMAIL_DOMAIN_VALUE = 16,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DMExportDataFormat", Namespace="http://schemas.datacontract.org/2004/07/DMLibrary")]
    public enum DMExportDataFormat : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMDF_CSV = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMDF_BCP = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompressionMethod", Namespace="http://schemas.datacontract.org/2004/07/DMLibrary.Streams")]
    public enum CompressionMethod : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CM_LZMA = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CM_BZIP2 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CM_GZIP = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CM_ZIP = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CM_NONE = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DMEventColumn", Namespace="http://schemas.datacontract.org/2004/07/DMLibrary")]
    [System.SerializableAttribute()]
    public partial class DMEventColumn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlterianEMAPIClient.DMPlus.DMEventColumnType ColumnTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FieldIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ListIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlterianEMAPIClient.DMPlus.DMEventColumnType ColumnType {
            get {
                return this.ColumnTypeField;
            }
            set {
                if ((this.ColumnTypeField.Equals(value) != true)) {
                    this.ColumnTypeField = value;
                    this.RaisePropertyChanged("ColumnType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FieldID {
            get {
                return this.FieldIDField;
            }
            set {
                if ((this.FieldIDField.Equals(value) != true)) {
                    this.FieldIDField = value;
                    this.RaisePropertyChanged("FieldID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ListID {
            get {
                return this.ListIDField;
            }
            set {
                if ((this.ListIDField.Equals(value) != true)) {
                    this.ListIDField = value;
                    this.RaisePropertyChanged("ListID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DMEventColumnType", Namespace="http://schemas.datacontract.org/2004/07/DMLibrary")]
    public enum DMEventColumnType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_EVENT_ID = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_EVENT_TIME = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_EVENT_NAME = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_EVENT_VALUE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_DEPLOYMENT_ID = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_DEPLOYMENT_NAME = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_DEPLOYMENT_STARTED = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_DEPLOYMENT_FINISHED = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_CREATIVE_ID = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_CREATIVE_NAME = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_CREATIVE_CATEGORY_ID = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_CREATIVE_CATEGORY_NAME = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_TEMPLATE_ID = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_TEMPLATE_NAME = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_LIST_ID = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_LIST_NAME = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_LIST_CATEGORY_ID = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_LIST_CATEGORY_NAME = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_RECIPIENT_ID = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_IP = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_OS = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_WB_TOKEN = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_WB_VALUE = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_INFO = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_FIELD_TOKEN = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_FIELD_VALUE = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_EMAIL_TOKEN = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_EMAIL_VALUE = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_EMAIL_HEALTH = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_EMAIL_DOMAIN_TOKEN = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMEC_EMAIL_DOMAIN_VALUE = 30,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DMPlus.DMPlus")]
    public interface DMPlus {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMPlus/CreateExportByList", ReplyAction="http://tempuri.org/DMPlus/CreateExportByListResponse")]
        AlterianEMAPIClient.DMPlus.CreateExportByListResponse CreateExportByList(AlterianEMAPIClient.DMPlus.CreateExportByListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMPlus/CreateExportByList", ReplyAction="http://tempuri.org/DMPlus/CreateExportByListResponse")]
        System.Threading.Tasks.Task<AlterianEMAPIClient.DMPlus.CreateExportByListResponse> CreateExportByListAsync(AlterianEMAPIClient.DMPlus.CreateExportByListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMPlus/CreateExportByDate", ReplyAction="http://tempuri.org/DMPlus/CreateExportByDateResponse")]
        AlterianEMAPIClient.DMPlus.CreateExportByDateResponse CreateExportByDate(AlterianEMAPIClient.DMPlus.CreateExportByDateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMPlus/CreateExportByDate", ReplyAction="http://tempuri.org/DMPlus/CreateExportByDateResponse")]
        System.Threading.Tasks.Task<AlterianEMAPIClient.DMPlus.CreateExportByDateResponse> CreateExportByDateAsync(AlterianEMAPIClient.DMPlus.CreateExportByDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMPlus/CreateExportByPK", ReplyAction="http://tempuri.org/DMPlus/CreateExportByPKResponse")]
        AlterianEMAPIClient.DMPlus.CreateExportByPKResponse CreateExportByPK(AlterianEMAPIClient.DMPlus.CreateExportByPKRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMPlus/CreateExportByPK", ReplyAction="http://tempuri.org/DMPlus/CreateExportByPKResponse")]
        System.Threading.Tasks.Task<AlterianEMAPIClient.DMPlus.CreateExportByPKResponse> CreateExportByPKAsync(AlterianEMAPIClient.DMPlus.CreateExportByPKRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMPlus/DeleteExport", ReplyAction="http://tempuri.org/DMPlus/DeleteExportResponse")]
        void DeleteExport(string Token, int ExportID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMPlus/DeleteExport", ReplyAction="http://tempuri.org/DMPlus/DeleteExportResponse")]
        System.Threading.Tasks.Task DeleteExportAsync(string Token, int ExportID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMPlus/ExportRecipientData", ReplyAction="http://tempuri.org/DMPlus/ExportRecipientDataResponse")]
        System.IO.Stream ExportRecipientData(string Token, int ExportID, int Page, AlterianEMAPIClient.DMPlus.DMRecipientColumn[] Columns, AlterianEMAPIClient.DMPlus.DMExportDataFormat Format, AlterianEMAPIClient.DMPlus.CompressionMethod Compression);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMPlus/ExportRecipientData", ReplyAction="http://tempuri.org/DMPlus/ExportRecipientDataResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> ExportRecipientDataAsync(string Token, int ExportID, int Page, AlterianEMAPIClient.DMPlus.DMRecipientColumn[] Columns, AlterianEMAPIClient.DMPlus.DMExportDataFormat Format, AlterianEMAPIClient.DMPlus.CompressionMethod Compression);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMPlus/ExportRecipientLists", ReplyAction="http://tempuri.org/DMPlus/ExportRecipientListsResponse")]
        System.IO.Stream ExportRecipientLists(string Token, int ExportID, int Page, int[] Lists, AlterianEMAPIClient.DMPlus.DMExportDataFormat Format, AlterianEMAPIClient.DMPlus.CompressionMethod Compression);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMPlus/ExportRecipientLists", ReplyAction="http://tempuri.org/DMPlus/ExportRecipientListsResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> ExportRecipientListsAsync(string Token, int ExportID, int Page, int[] Lists, AlterianEMAPIClient.DMPlus.DMExportDataFormat Format, AlterianEMAPIClient.DMPlus.CompressionMethod Compression);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMPlus/ExportFieldValues", ReplyAction="http://tempuri.org/DMPlus/ExportFieldValuesResponse")]
        System.IO.Stream ExportFieldValues(string Token, int ExportID, int Page, int FieldID, int ListID, AlterianEMAPIClient.DMPlus.DMExportDataFormat Format, AlterianEMAPIClient.DMPlus.CompressionMethod Compression);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMPlus/ExportFieldValues", ReplyAction="http://tempuri.org/DMPlus/ExportFieldValuesResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> ExportFieldValuesAsync(string Token, int ExportID, int Page, int FieldID, int ListID, AlterianEMAPIClient.DMPlus.DMExportDataFormat Format, AlterianEMAPIClient.DMPlus.CompressionMethod Compression);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMPlus/ExportEventlogDataByPage", ReplyAction="http://tempuri.org/DMPlus/ExportEventlogDataByPageResponse")]
        System.IO.Stream ExportEventlogDataByPage(string Token, int ExportID, int Page, System.DateTime DateFrom, System.DateTime DateTo, AlterianEMAPIClient.DMPlus.DMEventExportFilter[] Filters, AlterianEMAPIClient.DMPlus.DMEventColumn[] Columns, AlterianEMAPIClient.DMPlus.DMExportDataFormat Format, AlterianEMAPIClient.DMPlus.CompressionMethod Compression);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMPlus/ExportEventlogDataByPage", ReplyAction="http://tempuri.org/DMPlus/ExportEventlogDataByPageResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> ExportEventlogDataByPageAsync(string Token, int ExportID, int Page, System.DateTime DateFrom, System.DateTime DateTo, AlterianEMAPIClient.DMPlus.DMEventExportFilter[] Filters, AlterianEMAPIClient.DMPlus.DMEventColumn[] Columns, AlterianEMAPIClient.DMPlus.DMExportDataFormat Format, AlterianEMAPIClient.DMPlus.CompressionMethod Compression);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMPlus/ExportEventlogData", ReplyAction="http://tempuri.org/DMPlus/ExportEventlogDataResponse")]
        System.IO.Stream ExportEventlogData(string Token, int ExportID, System.DateTime DateFrom, System.DateTime DateTo, AlterianEMAPIClient.DMPlus.DMEventExportFilter[] Filters, AlterianEMAPIClient.DMPlus.DMEventColumn[] Columns, AlterianEMAPIClient.DMPlus.DMExportDataFormat Format, AlterianEMAPIClient.DMPlus.CompressionMethod Compression);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMPlus/ExportEventlogData", ReplyAction="http://tempuri.org/DMPlus/ExportEventlogDataResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> ExportEventlogDataAsync(string Token, int ExportID, System.DateTime DateFrom, System.DateTime DateTo, AlterianEMAPIClient.DMPlus.DMEventExportFilter[] Filters, AlterianEMAPIClient.DMPlus.DMEventColumn[] Columns, AlterianEMAPIClient.DMPlus.DMExportDataFormat Format, AlterianEMAPIClient.DMPlus.CompressionMethod Compression);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateExportByList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateExportByListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int PageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int[] Lists;
        
        public CreateExportByListRequest() {
        }
        
        public CreateExportByListRequest(string Token, int PageSize, int[] Lists) {
            this.Token = Token;
            this.PageSize = PageSize;
            this.Lists = Lists;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateExportByListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateExportByListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CreateExportByListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int Count;
        
        public CreateExportByListResponse() {
        }
        
        public CreateExportByListResponse(int CreateExportByListResult, int Count) {
            this.CreateExportByListResult = CreateExportByListResult;
            this.Count = Count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateExportByDate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateExportByDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int PageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime DateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.DateTime DateTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public AlterianEMAPIClient.DMPlus.DMEventExportFilter[] Filters;
        
        public CreateExportByDateRequest() {
        }
        
        public CreateExportByDateRequest(string Token, int PageSize, System.DateTime DateFrom, System.DateTime DateTo, AlterianEMAPIClient.DMPlus.DMEventExportFilter[] Filters) {
            this.Token = Token;
            this.PageSize = PageSize;
            this.DateFrom = DateFrom;
            this.DateTo = DateTo;
            this.Filters = Filters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateExportByDateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateExportByDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CreateExportByDateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int Count;
        
        public CreateExportByDateResponse() {
        }
        
        public CreateExportByDateResponse(int CreateExportByDateResult, int Count) {
            this.CreateExportByDateResult = CreateExportByDateResult;
            this.Count = Count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateExportByPK", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateExportByPKRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int PageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int PrimaryKey;
        
        public CreateExportByPKRequest() {
        }
        
        public CreateExportByPKRequest(string Token, int PageSize, int PrimaryKey) {
            this.Token = Token;
            this.PageSize = PageSize;
            this.PrimaryKey = PrimaryKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateExportByPKResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateExportByPKResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CreateExportByPKResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int Count;
        
        public CreateExportByPKResponse() {
        }
        
        public CreateExportByPKResponse(int CreateExportByPKResult, int Count) {
            this.CreateExportByPKResult = CreateExportByPKResult;
            this.Count = Count;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DMPlusChannel : AlterianEMAPIClient.DMPlus.DMPlus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DMPlusClient : System.ServiceModel.ClientBase<AlterianEMAPIClient.DMPlus.DMPlus>, AlterianEMAPIClient.DMPlus.DMPlus {
        
        public DMPlusClient() {
        }
        
        public DMPlusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DMPlusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DMPlusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DMPlusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AlterianEMAPIClient.DMPlus.CreateExportByListResponse AlterianEMAPIClient.DMPlus.DMPlus.CreateExportByList(AlterianEMAPIClient.DMPlus.CreateExportByListRequest request) {
            return base.Channel.CreateExportByList(request);
        }
        
        public int CreateExportByList(string Token, int PageSize, int[] Lists, out int Count) {
            AlterianEMAPIClient.DMPlus.CreateExportByListRequest inValue = new AlterianEMAPIClient.DMPlus.CreateExportByListRequest();
            inValue.Token = Token;
            inValue.PageSize = PageSize;
            inValue.Lists = Lists;
            AlterianEMAPIClient.DMPlus.CreateExportByListResponse retVal = ((AlterianEMAPIClient.DMPlus.DMPlus)(this)).CreateExportByList(inValue);
            Count = retVal.Count;
            return retVal.CreateExportByListResult;
        }
        
        public System.Threading.Tasks.Task<AlterianEMAPIClient.DMPlus.CreateExportByListResponse> CreateExportByListAsync(AlterianEMAPIClient.DMPlus.CreateExportByListRequest request) {
            return base.Channel.CreateExportByListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AlterianEMAPIClient.DMPlus.CreateExportByDateResponse AlterianEMAPIClient.DMPlus.DMPlus.CreateExportByDate(AlterianEMAPIClient.DMPlus.CreateExportByDateRequest request) {
            return base.Channel.CreateExportByDate(request);
        }
        
        public int CreateExportByDate(string Token, int PageSize, System.DateTime DateFrom, System.DateTime DateTo, AlterianEMAPIClient.DMPlus.DMEventExportFilter[] Filters, out int Count) {
            AlterianEMAPIClient.DMPlus.CreateExportByDateRequest inValue = new AlterianEMAPIClient.DMPlus.CreateExportByDateRequest();
            inValue.Token = Token;
            inValue.PageSize = PageSize;
            inValue.DateFrom = DateFrom;
            inValue.DateTo = DateTo;
            inValue.Filters = Filters;
            AlterianEMAPIClient.DMPlus.CreateExportByDateResponse retVal = ((AlterianEMAPIClient.DMPlus.DMPlus)(this)).CreateExportByDate(inValue);
            Count = retVal.Count;
            return retVal.CreateExportByDateResult;
        }
        
        public System.Threading.Tasks.Task<AlterianEMAPIClient.DMPlus.CreateExportByDateResponse> CreateExportByDateAsync(AlterianEMAPIClient.DMPlus.CreateExportByDateRequest request) {
            return base.Channel.CreateExportByDateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AlterianEMAPIClient.DMPlus.CreateExportByPKResponse AlterianEMAPIClient.DMPlus.DMPlus.CreateExportByPK(AlterianEMAPIClient.DMPlus.CreateExportByPKRequest request) {
            return base.Channel.CreateExportByPK(request);
        }
        
        public int CreateExportByPK(string Token, int PageSize, int PrimaryKey, out int Count) {
            AlterianEMAPIClient.DMPlus.CreateExportByPKRequest inValue = new AlterianEMAPIClient.DMPlus.CreateExportByPKRequest();
            inValue.Token = Token;
            inValue.PageSize = PageSize;
            inValue.PrimaryKey = PrimaryKey;
            AlterianEMAPIClient.DMPlus.CreateExportByPKResponse retVal = ((AlterianEMAPIClient.DMPlus.DMPlus)(this)).CreateExportByPK(inValue);
            Count = retVal.Count;
            return retVal.CreateExportByPKResult;
        }
        
        public System.Threading.Tasks.Task<AlterianEMAPIClient.DMPlus.CreateExportByPKResponse> CreateExportByPKAsync(AlterianEMAPIClient.DMPlus.CreateExportByPKRequest request) {
            return base.Channel.CreateExportByPKAsync(request);
        }
        
        public void DeleteExport(string Token, int ExportID) {
            base.Channel.DeleteExport(Token, ExportID);
        }
        
        public System.Threading.Tasks.Task DeleteExportAsync(string Token, int ExportID) {
            return base.Channel.DeleteExportAsync(Token, ExportID);
        }
        
        public System.IO.Stream ExportRecipientData(string Token, int ExportID, int Page, AlterianEMAPIClient.DMPlus.DMRecipientColumn[] Columns, AlterianEMAPIClient.DMPlus.DMExportDataFormat Format, AlterianEMAPIClient.DMPlus.CompressionMethod Compression) {
            return base.Channel.ExportRecipientData(Token, ExportID, Page, Columns, Format, Compression);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> ExportRecipientDataAsync(string Token, int ExportID, int Page, AlterianEMAPIClient.DMPlus.DMRecipientColumn[] Columns, AlterianEMAPIClient.DMPlus.DMExportDataFormat Format, AlterianEMAPIClient.DMPlus.CompressionMethod Compression) {
            return base.Channel.ExportRecipientDataAsync(Token, ExportID, Page, Columns, Format, Compression);
        }
        
        public System.IO.Stream ExportRecipientLists(string Token, int ExportID, int Page, int[] Lists, AlterianEMAPIClient.DMPlus.DMExportDataFormat Format, AlterianEMAPIClient.DMPlus.CompressionMethod Compression) {
            return base.Channel.ExportRecipientLists(Token, ExportID, Page, Lists, Format, Compression);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> ExportRecipientListsAsync(string Token, int ExportID, int Page, int[] Lists, AlterianEMAPIClient.DMPlus.DMExportDataFormat Format, AlterianEMAPIClient.DMPlus.CompressionMethod Compression) {
            return base.Channel.ExportRecipientListsAsync(Token, ExportID, Page, Lists, Format, Compression);
        }
        
        public System.IO.Stream ExportFieldValues(string Token, int ExportID, int Page, int FieldID, int ListID, AlterianEMAPIClient.DMPlus.DMExportDataFormat Format, AlterianEMAPIClient.DMPlus.CompressionMethod Compression) {
            return base.Channel.ExportFieldValues(Token, ExportID, Page, FieldID, ListID, Format, Compression);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> ExportFieldValuesAsync(string Token, int ExportID, int Page, int FieldID, int ListID, AlterianEMAPIClient.DMPlus.DMExportDataFormat Format, AlterianEMAPIClient.DMPlus.CompressionMethod Compression) {
            return base.Channel.ExportFieldValuesAsync(Token, ExportID, Page, FieldID, ListID, Format, Compression);
        }
        
        public System.IO.Stream ExportEventlogDataByPage(string Token, int ExportID, int Page, System.DateTime DateFrom, System.DateTime DateTo, AlterianEMAPIClient.DMPlus.DMEventExportFilter[] Filters, AlterianEMAPIClient.DMPlus.DMEventColumn[] Columns, AlterianEMAPIClient.DMPlus.DMExportDataFormat Format, AlterianEMAPIClient.DMPlus.CompressionMethod Compression) {
            return base.Channel.ExportEventlogDataByPage(Token, ExportID, Page, DateFrom, DateTo, Filters, Columns, Format, Compression);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> ExportEventlogDataByPageAsync(string Token, int ExportID, int Page, System.DateTime DateFrom, System.DateTime DateTo, AlterianEMAPIClient.DMPlus.DMEventExportFilter[] Filters, AlterianEMAPIClient.DMPlus.DMEventColumn[] Columns, AlterianEMAPIClient.DMPlus.DMExportDataFormat Format, AlterianEMAPIClient.DMPlus.CompressionMethod Compression) {
            return base.Channel.ExportEventlogDataByPageAsync(Token, ExportID, Page, DateFrom, DateTo, Filters, Columns, Format, Compression);
        }
        
        public System.IO.Stream ExportEventlogData(string Token, int ExportID, System.DateTime DateFrom, System.DateTime DateTo, AlterianEMAPIClient.DMPlus.DMEventExportFilter[] Filters, AlterianEMAPIClient.DMPlus.DMEventColumn[] Columns, AlterianEMAPIClient.DMPlus.DMExportDataFormat Format, AlterianEMAPIClient.DMPlus.CompressionMethod Compression) {
            return base.Channel.ExportEventlogData(Token, ExportID, DateFrom, DateTo, Filters, Columns, Format, Compression);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> ExportEventlogDataAsync(string Token, int ExportID, System.DateTime DateFrom, System.DateTime DateTo, AlterianEMAPIClient.DMPlus.DMEventExportFilter[] Filters, AlterianEMAPIClient.DMPlus.DMEventColumn[] Columns, AlterianEMAPIClient.DMPlus.DMExportDataFormat Format, AlterianEMAPIClient.DMPlus.CompressionMethod Compression) {
            return base.Channel.ExportEventlogDataAsync(Token, ExportID, DateFrom, DateTo, Filters, Columns, Format, Compression);
        }
    }
}
